[package]
name = "AppDataCleaner"
version = "1.0.3-b1"
edition = "2021"

[dependencies]
egui = "0.29.1"
eframe = "0.29.1"
dirs-next = "2.0"
tokio = { version = "1", features = ["full"] }
walkdir = "2.4"
log = "0.4"
simplelog = "0.12"
sha2 = "0.10"
native-dialog = "0.7.0"
