name: Bug 反馈
description: 功能运行不正常 / 失效
body:
 # - type: markdown
 #   attributes:
  #    value: |
        # 默认您已阅读 [Issues 须知](https://github.com/the1812/Bilibili-Evolved/blob/preview/doc/issue-rules.md)
        # 请勿重复发起, 发之前记得看下[置顶问题 (Pinned issues)](https://github.com/the1812/Bilibili-Evolved/issues) (如果有的话), 以及[常见问题解答](https://github.com/the1812/Bilibili-Evolved/discussions/1301)
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 如何重现此问题
      placeholder: 请输入
    validations:
      required: true
  - type: input
    id: software-version
    attributes:
      label: 软件版本
      description: 可在关于页面看到版本信息，不接受ci版本反馈
      placeholder: 请输入
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: 操作系统版本（只接受 Windows
      description: 例如 Windows 10
      placeholder: 请输入
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志信息
      description: |
        勾选开启日志记录后上传日志信息或者上传控制台输出
      render: Shell
      placeholder: 请输入
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 附加截图
      placeholder: 可在此粘贴图片
  - type: textarea
    id: kaikeitsuhou
    attributes:
      label: 解决方案
      description: |
        简述一下你的想法
      placeholder: 请输入
